# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch
  
env: 
  cloud: amazon

  # Allows you to run this workflow manually from the Actions tab
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  name_of_the_job:
    runs-on: ubuntu-latest
    env:
      greeting: hello
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        env: 
          name: pandi
      
      - name: variables
        run: echo"&cloud $greeting $name"
