name: variable
on:
  workflow_dispatch:
    inputs:
      num1:
        required: true
        type: number
      num2:
        required: true
        type: number

env: 
  cloud: Azure

jobs:
  name_of_the_job:
    runs-on: ubuntu-latest
    env:
      devenv: pandi
    steps:
      - name: Set variables
        env: 
          test: test
        run: |
          echo "$cloud $devenv $test"
          echo "${{ runner.name }}"
          echo "${{ github.actor }}"
      
      - name: Save state
        run: echo "::save-state name=my_sum::$((${{ github.event.inputs.num1 }} + ${{ github.event.inputs.num2 }}))"
      
      - name: Print my_sum and secret
        run: |
          echo "The sum is ${{ state.my_sum }}"
          echo "Secret Value: ${{ secrets.MY_KEY }}"
