name: CI
on:
  workflow_dispatch
    
env: 
  cloud: Azure

jobs:
  name_of_the_job:
    runs-on: ubuntu-latest
    env:
      greeting: hello
    steps:
      env: 
          name: pandi
      - name: variables
        run: echo"&cloud $greeting $name"
