name: CI
on:
  workflow_dispatch

env: 
  cloud: Azure
inputs:
  num1:
  required: true
  num2:
  required: true
jobs:
  name_of_the_job:
    runs-on: ubuntu-latest
    env:
      devenv: pandi
    steps:
      - name: Set variables
        env: 
          test: test
        run: |
          echo "$cloud $devenv $test"
          echo "${{ runner.name }}"
          echo "${{ github.actor }}"
          echo "${{ vars.kp }}"
      
    - name: Add numbers
        id: sum
        run: echo "::set-output name=sum::$((${{ inputs.num1 }} + ${{ inputs.num2 }}))"
