name: CI
on:
  workflow_dispatch 
env: 
  cloud: Azure
jobs:
  name_of_the_job:
    runs-on: ubuntu-latest
    env:
      devenv: pandi
    steps:
      env: 
          test: test
      - name: variables
        run: echo"&cloud $devenv $test"
