name: CI
on:
  workflow_dispatch

env: 
  cloud: Azure

jobs:
  name_of_the_job:
    runs-on: ubuntu-latest
    env:
      devenv: pandi
    steps:
      - name: Set variables
        env: 
          test: test
        run: |
          echo "$cloud $devenv $test"
          echo "${{ github.runner.name }}"
          echo "${{ github.triggering_actor }}"
